---
Name: tinymce-config
---
SilverStripe\Forms\HTMLEditor\HTMLEditorConfig:
  default_config_definitions:
    cms:
      configClass: 'SilverStripe\TinyMCE\TinyMCEConfig'

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'silverstripe/htmleditor-tinymce: client/dist/js/bundle.js'

SilverStripe\TinyMCE\TinyMCEConfig:
  premium_api_key: '`TINYMCE_API_KEY`'